language: java

jdk:
 - openjdk11

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - 1841187753@qq.com

deploy:
  provider: releases
  tag_name: "v0.0.0"
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    tags: true