language: java

jdk:
 - openjdk11

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - 1841187753@qq.com

deploy:
  provider: releases
  file_glob: true
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file:
    - src
  on:
    tags: true
    branch: master
    repo: kreattang/Test_maven_travis_ci
